name: Flutter Release

permissions:
  contents: write
  actions: read
  id-token: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Write amplify_outputs.dart from secret
        run: |
          echo "${{ secrets.AMPLIFY_OUTPUTS_DART }}" > lib/amplify_outputs.dart

      # - name: Run tests
        # run: flutter test

      - name: Build split APKs
        run: flutter build apk --split-per-abi

      - name: List APKs
        run: ls -lh build/app/outputs/flutter-apk/

      - name: Upload APKs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: split-apks
          path: build/app/outputs/flutter-apk/*.apk

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # --- Release Step ---
      - name: Create GitHub Release and Upload APKs
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
