name: oflow
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+3
environment:
  sdk: ">=3.1.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.3.0
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  wheel_picker: ^0.1.1
  mqtt5_client: ^4.14.0
  shared_preferences: ^2.3.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  http: ^1.2.2
  crypto: ^3.0.6
  convert: ^3.1.2
  amplify_flutter: ^2.3.1
  amplify_authenticator: ^2.3.1
  amplify_auth_cognito: ^2.3.1
  url_launcher: ^6.3.1
  logger: ^2.5.0
  uuid: ^4.5.1
  mobile_scanner: ^6.0.3
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/urbanist/Urbanist-Black.ttf
          weight: 900
